name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.1', '3.0', '2.7', '2.6', '2.5']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install Bundler
        run: |
          gem install bundler
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install Ruby deps
        run: |
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: |
          bundle exec rspec
      - name: Run RSpec (prepended)
        run: |
          bundle exec rspec -r all_prepend
